Init
SergeyIsmagilov/layout-designer-project-lvl1 pull request #2
Opened 2022-06-08 14:23 UTC by SergeyIsmagilov

2022-06-08 15:04 UTC, dez64ru requested changes

2022-06-08 15:04 UTC, dez64ru commented on src/styles/style.css
> +  --mainblack: #2a2626;
Используй или camelCase (лучше это) или kebab-case.

2022-06-08 15:04 UTC, bushaev-denis commented on src/styles/style.css
> +  --orange-hover: #ea7600;
Если решишь использовать camelCase исправь тут тоже.

2022-06-08 15:04 UTC, dez64ru commented on src/styles/style.css
> +  color: var(--mainblack);
Ну и тут.

2022-06-09 00:00 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  --mainblack: #2a2626;
У меня по условиям прохождения проекта линтер настроен на kebab-case.
Но вообще я хотел бы придерживаться структуры, вроде "объект_свойство-разновидностьсвойства" (не обязательно в таком порядке). Суть в том, чтобы было видно уровень наименования по способу разделения (сложно объяснить без опыта). Надеюсь, понятно.

2022-06-09 00:01 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  --orange-hover: #ea7600;
То есть тут у меня цвет-подвид(разновидность) этого же цвета.

2022-06-09 00:02 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  color: var(--mainblack);
Тогда в этом проекте буду придерживаться kebab-case.

2022-06-10 08:36 UTC, merged