Header
SergeyIsmagilov/layout-designer-project-lvl1 pull request #3
Opened 2022-06-08 14:30 UTC by SergeyIsmagilov

2022-06-08 15:15 UTC, dez64ru requested changes

2022-06-08 15:15 UTC, dez64ru commented on src/styles/style.css
> +.margin-top-200 { /* как назвать этот класс и подобные? */
Предлагаю сократить такое до mt-{value}
```css
p-0 {padding: 0px}
pt-0 {padding-top: 0px} /* pt,pr,pb,pl -- аналогично */
px-0 {padding-left: 0px; padding-right: 0px}
py-0 = {padding-top: 0px; padding-bottom: 0px}
/* m,mt,mr,mb,ml,mx,my -- аналогично */
mx-auto {margin: 0 auto}
```

2022-06-08 15:15 UTC, dez64ru commented on src/styles/style.css
> +/* по какой логике группировать классы??? */
Давай предложу 3 группы:
-- base
-- utils
-- block name

2022-06-08 15:15 UTC, dez64ru commented on src/styles/style.css
> +  margin: 0 auto; /* есть более правильный способ выровнять блок по центру страницы? есть проблемы с этим? */
Убери комментарий, мы уже решили ранее этот вопрос.

2022-06-08 15:15 UTC, dez64ru commented on src/styles/style.css
> +.margin-top-200 { /* как назвать этот класс и подобные? */
Когда сделаешь все это - посмотрю что получается.

2022-06-09 00:38 UTC, SergeyIsmagilov commented on src/styles/style.css
> +/* по какой логике группировать классы??? */
Пока не понимаю.

2022-06-09 06:23 UTC, dez64ru commented on src/styles/style.css
> +/* по какой логике группировать классы??? */
base - сброс стилей, шрифты, глобальные стили.
utils - все утилитарные классы colors, pt, py....
block name - поблочные стили, на каждый блок своя группа

2022-06-09 11:03 UTC, dez64ru requested changes

2022-06-09 11:03 UTC, bushaev-denis commented on src/index.html
> +                    <a class="details" href="#navigation">ПОДРОБНЕЕ</a>
Убери капс в контенте, сделай через css

2022-06-09 11:03 UTC, dez64ru commented on src/styles/style.css
> +  columns: 2;
см. ниже

2022-06-09 11:03 UTC, dez64ru commented on src/styles/style.css
> +  break-inside: avoid;
Используй флексы для такого, с ним таких проблем как с columns.

2022-06-09 11:03 UTC, dez64ru commented on src/styles/style.css
> +  overflow: hidden;
Лишний стиль, вроде бы. Не вижу никакой разницы если отключаю его.

2022-06-10 00:48 UTC, SergeyIsmagilov commented on src/index.html
> +                    <a class="details" href="#navigation">ПОДРОБНЕЕ</a>
Сделал. А почему капс в контенте - плохо?

2022-06-10 00:53 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  break-inside: avoid;
В данном случае так правильнее.

2022-06-10 01:03 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  break-inside: avoid;
1. Это напрямую указано в заданиях.
2. Мне понадобится больше свойств, чтобы сделать то же через flex.

2022-06-10 01:07 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  overflow: hidden;
Появляется горизонтальный скролл из-за размеров картинки.

2022-06-10 08:28 UTC, dez64ru commented on src/styles/style.css
> +  overflow: hidden;
А, да, че-то не так проверял.

2022-06-10 08:36 UTC, dez64ru commented on src/index.html
> +                    <a class="details" href="#navigation">ПОДРОБНЕЕ</a>
Поисковики парсят твой капс и потом в результатах выдают капсом сниппеты по запросу, выглядит не очень)

2022-07-04 12:56 UTC, dez64ru requested changes

2022-07-04 12:56 UTC, dez64ru commented on src/index.html
> +            <div class="columns-bottom mt-200">
Выбери один из стилей нейминга классов для всего проекта и используй только его. Не смешивай разные подходы.

2022-07-06 13:40 UTC, merged