video section
SergeyIsmagilov/layout-designer-project-lvl1 pull request #4
Opened 2022-07-06 14:26 UTC by SergeyIsmagilov

2022-07-06 20:48 UTC, dez64ru commented
@SergeyIsmagilov переименуй pr, init тут неуместно.

2022-07-06 21:26 UTC, dez64ru requested changes
тест

2022-07-06 21:52 UTC, dez64ru requested changes
тест2

2022-07-06 22:24 UTC, dez64ru requested changes

2022-07-06 22:24 UTC, dez64ru commented on src/index.html
> +        <nav style="width: 1110px; height: 200px; background-color: black; margin: 0 auto;"> <!--нужно показать, что видео накладывается на следующую секцию-->
Этот коммент не о качестве кода, но о качестве pr.
В таком случае ставится в начале коммента спец. тэг ```FIXME```, ```TODO```, ```REVIEW``` ...etc (нагугли, их много), в данном случае FIXME или TODO, т.к. это нереализованный функционал и коммент следует убрать в будущем.

```<!--TODO: нужно показать, что видео накладывается на следующую секцию-->```

2022-07-06 22:24 UTC, dez64ru commented on src/index.html
> +            <iframe class="video drop-shadow mt-30" width="919" height="569" src="https://www.youtube.com/embed/jie9AizBqss" frameborder="0" allowfullscreen></iframe> <!--в шаге проекта указано, что
Понял, не забудь убрать коммент

2022-07-06 22:24 UTC, dez64ru commented on src/index.html
> +            <h2><span class="color-main">Что же это такое,<br></span>когнитивные искажения?</h2>
```</span><br>```

2022-07-06 22:24 UTC, dez64ru commented on src/styles/style.css
> +  margin-top: 30px;
Отсортируй классы ```mt-15, mt-30, mt-200....```

2022-07-06 22:24 UTC, dez64ru commented on src/styles/style.css
> +.displacement {
используй padding-top, тогда от этого класса вообще можно избавиться

2022-07-07 06:37 UTC, SergeyIsmagilov commented on src/styles/style.css
> +.displacement {
Ты забыл, что видео должно накладываться на следующую секцию.

2022-07-07 08:11 UTC, dez64ru commented on src/styles/style.css
> +.displacement {
Да, не учел. Тогда в этом случае лучше сделать как я написал выше + добавить класс ```-mb-100``` (- в начале класса неспроста 🙂

2022-07-07 08:14 UTC, dez64ru requested changes

2022-07-07 08:14 UTC, dez64ru commented on src/styles/style.css
> +.displacement {
Да, не учел. Тогда в этом случае лучше сделать как я написал выше + добавить класс ```-mb-100``` (- в начале класса неспроста 🙂

2022-07-07 09:25 UTC, dez64ru requested changes

2022-07-07 09:25 UTC, dez64ru commented on src/styles/style.css
> +.text-c {
лучше ```center```

2022-07-07 09:27 UTC, bushaev-denis commented on src/styles/style.css
> +.text-c {
В случае ```pt, pl, mb ...``` - это общепризнаные сокращения, всем сразу понятно что имеется в виду, а тут не очевидно, что это за ```c```

2022-07-07 10:00 UTC, dez64ru requested changes

2022-07-07 10:00 UTC, dez64ru commented on src/styles/style.css
> +.drop-shadow {
почему ```drop-shadow```? а не ```box-shadow```? ```box-shadow``` менее прожорливый

2022-07-07 10:00 UTC, dez64ru commented on src/index.html
> +            <iframe class="video drop-shadow mt-30" width="919" height="569" src="https://www.youtube.com/embed/jie9AizBqss" frameborder="0" allowfullscreen></iframe>
Класс ```video``` лишний?

2022-07-07 11:16 UTC, SergeyIsmagilov commented on src/styles/style.css
> +.drop-shadow {
В шаге проекта указали скопировать эту строчку.

2022-07-07 11:20 UTC, SergeyIsmagilov commented on src/index.html
> +            <iframe class="video drop-shadow mt-30" width="919" height="569" src="https://www.youtube.com/embed/jie9AizBqss" frameborder="0" allowfullscreen></iframe>
Опять же, в шаге проекта, где нужно было скопировать эту строчку, был этот класс.

2022-07-07 13:24 UTC, dez64ru approved these changes

2022-07-07 13:24 UTC, merged