ikea effect
SergeyIsmagilov/layout-designer-project-lvl1 pull request #6
Opened 2022-07-08 13:51 UTC by SergeyIsmagilov

2022-07-08 15:21 UTC, dez64ru commented on src/styles/style.css
> +.color-dark-half { /* может, назвать переменную darkhalf, чтобы название класса было с одним дефисом? */
обычно называют не half, а semi. ```.color-semi-dark```, css переменную тоже можешь так переименовать. Но как хочешь, дело твоего вкуса.

2022-07-08 15:21 UTC, dez64ru commented on src/styles/style.css
> +.color-dark-half { /* может, назвать переменную darkhalf, чтобы название класса было с одним дефисом? */
обычно называют не half, а semi. ```.color-semi-dark```, css переменную тоже можешь так переименовать. Но как хочешь, дело твоего вкуса.

2022-07-08 16:07 UTC, dez64ru commented on src/styles/style.css
> +
если приложение разрастется и будешь активно использовать флексы и гриды, то использовать align-* будет очень дорого, т.к. с флексами и гридами часто используется align-items.

2022-07-08 16:19 UTC, dez64ru requested changes

2022-07-08 16:19 UTC, dez64ru commented on src/styles/style.css
> +.p-neucha { /* а для параграфа со свойствами заголовка? */
```css
.font-neucha {}
.text-34 {}
.leading-12 {}
```

2022-07-08 16:19 UTC, dez64ru commented on src/styles/style.css
> +.h0 { /* как бы ты назвал класс для такого псевдозаголока? */
```css
.text-24 {}
.font-neucha {}
.leading-12 {}
````

2022-07-08 16:19 UTC, dez64ru commented on src/styles/style.css
> +  line-height: 1.2em;
em можно опускать.

2022-07-08 16:19 UTC, dez64ru commented on src/styles/style.css
> +  column-gap: 30px;
```css
.flex {}
.columns-2 {}
.gap-x-30 {}
```

2022-07-11 12:03 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  line-height: 1.2em;
В описании шага размер был указан с "em".

2022-07-14 09:58 UTC, dez64ru requested changes

2022-07-14 09:58 UTC, bushaev-denis commented on src/index.html
> +                        <h2 class="color-main">Эффект ИКЕА</h2>
Было бы хорошо избавиться от зависимости цвета по тегу, чтоб не переназначать цвет каждый раз для h2

2022-07-19 18:05 UTC, SergeyIsmagilov commented on src/index.html
> +                        <h2 class="color-main">Эффект ИКЕА</h2>
Так?

2022-07-19 18:23 UTC, merged