four similar sections
SergeyIsmagilov/layout-designer-project-lvl1 pull request #7
Opened 2022-07-20 12:38 UTC by SergeyIsmagilov

2022-07-21 07:46 UTC, dez64ru requested changes

2022-07-21 07:46 UTC, dez64ru commented on src/index.html
> +        <section class="bg-brown color-white">
У тебя тут беда прям с секциями.
Я думаю, необходимо убрать эти вложенные ::before

### html:
```html
<section class="bg-brown-10 bg-image color-white">....</section>
```

### css:
```css
::root {
  --brown-rgba: 176, 154, 129;
}
.bg-brown-10 {
  background-color: rgba(var(--brown-rgba), .1)
}
```

2022-07-21 12:59 UTC, SergeyIsmagilov commented on src/index.html
> +        <section class="bg-brown color-white">
Ты проверяешь свой код перед тем, как посоветовать его использовать?

2022-07-21 13:04 UTC, SergeyIsmagilov commented on src/index.html
> +        <section class="bg-brown color-white">
Если у тебя всё отлично, тогда я чего-то не понимаю. Обсудим проблемы в мессенджере.

2022-07-22 18:05 UTC, dez64ru approved these changes

2022-07-22 18:07 UTC, merged