Footer
SergeyIsmagilov/layout-designer-project-lvl1 pull request #8
Opened 2022-07-25 12:48 UTC by SergeyIsmagilov

2022-07-26 07:59 UTC, dez64ru requested changes

2022-07-26 07:59 UTC, bushaev-denis commented on src/index.html
> +        <div class="container py-100">
можно убрать внутренний div.container
Так же можно убрать mt-55 у нижнего блока, добавив сюда ```flex flex-col gap-y-55```

2022-07-26 07:59 UTC, bushaev-denis commented on src/index.html
> +            <div class="flex justify-content-space-between bg-dark color-white"> <!--Колонки или флексы?-->
Флексы. Колонками вообще не пользуйся, не вижу ни 1 преимущества в их использовании.

2022-07-26 07:59 UTC, bushaev-denis commented on src/index.html
> +            <div class="text-center text-14 mt-70">
Давай заменим эти повторяющиеся margin на ```<div class="flex flex-col gap-y-15 text-center text-14"...```

2022-07-26 07:59 UTC, dez64ru commented on src/index.html
> +            <div class="flex justify-content-space-between bg-dark color-white"> <!--Колонки или флексы?-->
```.justify-between {}```

2022-07-26 07:59 UTC, dez64ru commented on src/index.html
> +            <div class="flex justify-content-space-between bg-dark color-white"> <!--Колонки или флексы?-->
Давай начнем переверстку, напишу примерное видиние псевдокодом, потом если не получится сделать самому - созвонимся - вместе доделаем.
```html
<footer class="container py-100 flex flex-col gap-y-55">
    <div class="flex justify-between p-55 bg-dark color-white">
      <div class="w-485">
        <p class="text-18 leading-16">...</p>
        <form class="flex">
            <input class="w-full"> 
            <button class="..."></button>
        </form>
      </div>
      <div class="flex flex-col gap-y-15 mt-15 text-center text-14">
        ...
      </div>
    </div>
</footer>
```

2022-07-26 07:59 UTC, dez64ru commented on src/styles/style.css
> +.a { /* ??? */
Просто замени на тег (не забудь перенести это дело в нужный блок после этого).  Это нормальная практика сбрасывать стили для ссылок.

2022-07-26 07:59 UTC, dez64ru commented on src/styles/style.css
> +  cursor: pointer;
Этого не требуется, у button по-умолчанию pointer если не ```disable```

2022-08-23 12:04 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  cursor: pointer;
Но у меня курсор не меняется на pointer. Наверное, потому что над button у нас псевдоэлемент.

2022-09-18 13:48 UTC, dez64ru commented on src/styles/style.css
> +  cursor: pointer;
pointer-events: none; для псевдоэлемента.

2022-09-18 13:56 UTC, dez64ru commented on src/index.html
> +    <footer class="container py-100 flex flex-col gap-y-55"> <!--Вместо одного отптупа снизу мы добавили тут три класса и оставили отступ снизу, просто уменьшив его. Не проще было бы просто оставить
Ну тут, возможно я перегнул (хотя оба варианты примемлимы, дело стиля).

2022-09-18 13:56 UTC, dez64ru commented on src/index.html
> +                    <input class="w-full p-15 border-0" type="email" placeholder="Ваша электронная почта"> <!--Наверное, здесь нужен flex-grow.-->
Почему не добавил, если считаешь, что нужен?

2022-09-18 13:57 UTC, dez64ru commented on src/index.html
> +        <div class="border-1 mt-5 flex flex-col gap-y-15 py-15 text-center text-14"> <!--Добавили четыре класса, когда можно было просто три раза использовать один. Это снова выглядит, как излишнее у
А вот тут не выглядит. Когда тебе дизайнер пришлет новый вариант дизайна, где тебе нужно будет исправить этот отступ, ты, возможно, вспомнишь это.

2022-09-18 14:20 UTC, dez64ru commented on src/index.html
> +                <p class="text-18 leading-16">Электронная почта</p> <!--Наверное, правильнее было бы использовать <label>, но у меня не получилось сделать его таким же, как на эталонном скриншоте-->
Да, в идеале label, почему не получилось?

2022-09-18 14:20 UTC, dez64ru commented on src/index.html
> +            <div class="w-485 mr-55"> <!--Я почти уверен, что не должен указывать так много конкретных значений, в большой части проекта всё само становится на свои места, когда находишь правильный п
Можно убрать w-485, когда добавишь flex-grow для form, все встанет на свои места

2022-09-18 18:32 UTC, dez64ru commented on src/index.html
> +            <div class="w-485 mr-55"> <!--Я почти уверен, что не должен указывать так много конкретных значений, в большой части проекта всё само становится на свои места, когда находишь правильный п
и нужно будет добавить еще вертикальное выравнивание по центру.

2022-09-19 06:33 UTC, SergeyIsmagilov commented on src/styles/style.css
> +  cursor: pointer;
Видимо, дело не в псевдоэлементе. Если его убрать, без свойства pointer над button будет обычный курсор.

Сейчас отдельно проверил тег button в двух браузерах. "Этого не требуется, у button по-умолчанию pointer если не disable" - это не так.

2022-09-19 08:06 UTC, SergeyIsmagilov commented on src/index.html
> +        <div class="border-1 mt-5 flex flex-col gap-y-15 py-15 text-center text-14"> <!--Добавили четыре класса, когда можно было просто три раза использовать один. Это снова выглядит, как излишнее у
Понял.

2022-09-19 09:54 UTC, SergeyIsmagilov commented on src/index.html
> +                    <input class="w-full p-15 border-0" type="email" placeholder="Ваша электронная почта"> <!--Наверное, здесь нужен flex-grow.-->
Сомневался, что нет более подходящего способа сделать это.

2022-09-19 09:55 UTC, SergeyIsmagilov commented on src/index.html
> +                <p class="text-18 leading-16">Электронная почта</p> <!--Наверное, правильнее было бы использовать <label>, но у меня не получилось сделать его таким же, как на эталонном скриншоте-->
Уже не помню.

2022-09-19 10:16 UTC, SergeyIsmagilov commented on src/index.html
> +        <div class="container py-100">
"можно убрать внутренний div.container" - тесты не проходят, если свойство container на футере, так что пришлось вернуть.

2022-09-20 06:52 UTC, dez64ru commented
[#https://github.com/SergeyIsmagilov/layout-designer-project-lvl1/pull/8/commits/ac66345ba842689d8cbb3de9a701c315d2c1dfc6](https://github.com/SergeyIsmagilov/layout-designer-project-lvl1/pull/8/commits/ac66345ba842689d8cbb3de9a701c315d2c1dfc6), просто на будущее - очень не желательно вносить изменения в репо, которые не относятся к текущему пр, ты размазываешь контекст. Обычно просят удалить все, что не относится к текущему пр.

2022-09-20 06:54 UTC, dez64ru commented on src/styles/style.css
> +  cursor: pointer;
потому что сейчас это не button как таковой, у него действия нет. добавь ```type="submit"```

2022-09-20 06:59 UTC, dez64ru commented on src/index.html
> +        <div class="container py-100">
Почему тесты не проходят? Позиционирование одинаковое получается же.
<details>
<summary>слева footer.container, справа footer>div.container</summary>

![Screenshot 2022-09-20 at 09 58 30](https://user-images.githubusercontent.com/32451886/191188646-3f4c81c6-f7a4-4be8-8c10-75f1aa4b88ce.png)
</details>

2022-09-20 06:59 UTC, dez64ru approved these changes

2022-09-20 09:42 UTC, SergeyIsmagilov commented on src/index.html
> +        <div class="container py-100">
Да, но тесты, как я понимаю, генерируют каждую секцию по отдельности и получается <details><summary>вот так:</summary>
![index-test-js-screenshots-sections-with-a-viewport-width-of-1440-px-footer-section-1-diff](https://user-images.githubusercontent.com/95710486/191219994-f749f440-d6ca-4e50-901e-ed7e950e1f44.png)</details>

2022-09-20 10:00 UTC, merged